<?php

namespace diform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-05-20 at 08:11:32.
 */
class configTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers diform\config::extend
     * @todo   Implement testExtend().
     */
    public function testExtend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\config::lang
     * @todo   Implement testLang().
     */
    public function testLang() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\config::form
     * @todo   Implement testForm().
     */
    public function testForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\config::controls
     * @todo   Implement testControls().
     */
    public function testControls() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\config::template
     * @todo   Implement testTemplate().
     */
    public function testTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
