<?php

namespace diform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-06-20 at 09:06:27.
 */
class dataTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new data;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers diform\data::extend
     * @todo   Implement testExtend().
     */
    public function testExtend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\data::isPopulated
     * @todo   Implement testIsPopulated().
     */
    public function testIsPopulated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\data::value
     * @todo   Implement testValue().
     */
    public function testValue() {
        
        $form   = diform()->chain()
            ->text('a')
            ->text('b[a]')
        ;
        
        $this->assertEquals(array(), 
            diform()->chain()
            ->text('a')
            ->text('b[a]')
            ->data()
            ->value()
        );
        
        $_POST  =   array('a' => 'value', 'b' => 'not_taken');
        
        $this->assertEquals(
            array('a' => 'value'), 
            diform()->chain()
                ->text('a')
                ->text('b[a]')
                ->data()
                ->value()
        );
        
        $_POST  =   array('a' => 'value', 'b' => array('a' => 'taken'));
        
        $this->assertEquals(
            array('a' => 'value', 'b' => array('a' => 'taken')), 
            diform()->chain()
                ->text('a')
                ->text('b[a]')
                ->data()
                ->value()
        );
        
        
        $_POST  =   array(
            'a' => 'value', 'b' => array('a' => array('a', 'c')), 'dummy' => 'dummy');
        
        $this->assertEquals(
            array('a' => 'value', 'b' => array('a' => array('a', 'c'))), 
            diform()->chain()
                ->text('a')
                ->checkboxes('b[a]', null, array('choices' => array('a', 'b', 'c')))
                ->data()
                ->value()
        );
        
        $_POST  =   array(
            'a' => 'value', 
            'b' => array('a' => array('a', 'c')), 
            'dummy' => 'dummy');
        
        $this->assertEquals(
            array('a' => 'value', 'b' => array('a' => array('a', 'c'))), 
            diform()->chain()
                ->text('a')
                ->select('b[a]', null, array(
                    'multiple' => true,
                    'choices' => array('a', 'b', 'c')
                ))
                ->data()
                ->value()
        );
    }

    /**
     * @covers diform\data::request
     * @todo   Implement testRequest().
     */
    public function testRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\data::raw
     * @todo   Implement testRaw().
     */
    public function testRaw() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
