<?php

namespace diform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-05-20 at 08:11:31.
 */
class exceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var exception
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new exception;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
