<?php

namespace diform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-05-20 at 08:11:33.
 */
class extendableTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var extendable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new extendable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers diform\extendable::extend
     * @todo   Implement testExtend().
     */
    public function testExtend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
