<?php

namespace diform;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-05-20 at 08:11:29.
 */
class validatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var validator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new validator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers diform\validator::rule
     * @todo   Implement testRule().
     */
    public function testRule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\validator::is_disabled
     * @todo   Implement testIs_disabled().
     */
    public function testIs_disabled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\validator::rules4Attribute
     * @todo   Implement testRules4Attribute().
     */
    public function testRules4Attribute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\validator::checkValidity
     * @todo   Implement testCheckValidity().
     */
    public function testCheckValidity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\validator::feedback4ControlAndRule
     * @todo   Implement testFeedback4ControlAndRule().
     */
    public function testFeedback4ControlAndRule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\validator::lang4Control
     * @todo   Implement testLang4Control().
     */
    public function testLang4Control() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\validator::feedbacks
     * @todo   Implement testFeedbacks().
     */
    public function testFeedbacks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers diform\validator::rules
     * @todo   Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
