<?php
namespace diform\control;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-06-25 at 19:04:13.
 */
class selectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var select
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new select;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers diform\control\select::attrs
     * @todo   Implement testAttrs().
     */
    public function testAttrs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
